version: "3.3"
services:

  db:
    environment:
      - POSTGRES_DB=test

  backend:
    volumes:
      - ./app:/app
    command: bash -c "python shopping_list/init.py && uvicorn --reload --host 0.0.0.0 shopping_list.api.web:app"
